### ISSUE TITLE
Error loading the plugin `cocoapods-rome-0.7.0`.

### ISSUE THREAD

**Issue by RafaelPlantard** [CocoaPods/Rome#51]
`pod install` is generating this issue:

``` shell
---------------------------------------------
Error loading the plugin `cocoapods-rome-0.7.0`.

Gem::ConflictError - Unable to activate cocoapods-rome-0.7.0, because fourflusher-2.0.1 conflicts with fourflusher (~> 1.0.0)
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `map'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:326:in `block in run'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `each'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.3.1/bin/pod:22:in `load'
/usr/local/opt/rbenv/versions/2.3.1/bin/pod:22:in `<main>'
---------------------------------------------
```

**Comment by klaas** [comment]
Any chance to see #53 get pulled soon?

**Comment by segiddins** [comment]
@klaas it's just awaiting review
