### ISSUE TITLE
Fails in `integrate_targets=`

### ISSUE THREAD

**Issue by soffes** [CocoaPods/Rome#54]
### Command

```
/Users/soffes/.rbenv/versions/2.3.3/bin/pod install --repo-update
```

### Report

* What did you do?

    Tried to run `pod install --repo-update`

* What did you expect to happen?

    Built frameworks in the `Rome` directory.

* What happened instead?

    This error.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.5.2
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2 (8C38)
         Git : git version 2.11.0
Ruby lib dir : /Users/soffes/.rbenv/versions/2.3.3/lib
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 0.3.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

plugin 'cocoapods-rome'

target 'Caesar' do
  pod 'Alamofire'
end
```

### Error

```
NoMethodError - undefined method `integrate_targets=' for #<Pod::Config:0x007fdcae14f338>
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-rome-0.3.0/lib/cocoapods-rome/pre_install.rb:3:in `block in <top (required)>'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:463:in `run_plugins_pre_install_hooks'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:135:in `block in prepare'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:131:in `prepare'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:109:in `install!'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/soffes/.rbenv/versions/2.3.3/bin/pod:22:in `load'
/Users/soffes/.rbenv/versions/2.3.3/bin/pod:22:in `<top (required)>'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/soffes/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/Users/soffes/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/soffes/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
```

**Comment by segiddins** [comment]
Can you try update Rome to the latest release? Thanks!

**Comment by soffes** [comment]
Just did `gem install cocoapods-rome` before trying. Weird that I got an old version. Definitely never had it installed on this computer or bundle before.

Just decided to not use Rome/CocoaPods for this project for now though so closing. If someone else runs into it, I'm sure they'll report it.
