### ISSUE TITLE
Error when trying to build the sample

### ISSUE THREAD

**Issue by deepumukundan** [CocoaPods/Rome#64]
Got the below error when trying to install Alamofire as specified in the code sample.
Then I commented out line 73 which was calling the crashing method cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:73 and it worked. Looks like build_settings is getting nil.

### Error

```
NoMethodError - undefined method `build_settings' for nil:NilClass
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:44:in `block in enable_debug_information'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:42:in `each'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:42:in `enable_debug_information'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:73:in `block in <top (required)>'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:455:in `run_plugins_post_install_hooks'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:433:in `perform_post_install_actions'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:125:in `install!'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Users/dmukundan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/Users/dmukundan/.rbenv/versions/2.5.1/bin/pod:23:in `load'
/Users/dmukundan/.rbenv/versions/2.5.1/bin/pod:23:in `<main>'

**Output of pod env:**

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.17.0
Ruby lib dir : /Users/dmukundan/.rbenv/versions/2.5.1/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ f16ce0e4d635a3219b4e52d79b1e0d257b43b8fe
               master - https://github.com/CocoaPods/Specs.git @ 1fd514cb3076fb72490110206941e3c4466debcc
```

### Installation Source

```
Executable Path: /Users/dmukundan/.rbenv/versions/2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'

plugin 'cocoapods-rome'

target 'caesar' do
  pod 'Alamofire'
end
```

**Comment by Ruenzuo** [comment]
I wonder why the build settings in the Pods projects doesn't exist. I'll try to reproduce this myself, meanwhile you can opt-out of dSYM generation with `dsym: false` in your Podfile and avoid this error.
